//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SW.Objects.AR.Descriptor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SW.Objects.AR.Descriptor.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be greater than Document Date..
        /// </summary>
        internal static string ApplDate_Greater_DocDate {
            get {
                return ResourceManager.GetString("ApplDate_Greater_DocDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be less than Document Date..
        /// </summary>
        internal static string ApplDate_Less_DocDate {
            get {
                return ResourceManager.GetString("ApplDate_Less_DocDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be greater than Document Period..
        /// </summary>
        internal static string ApplPeriod_Greater_DocPeriod {
            get {
                return ResourceManager.GetString("ApplPeriod_Greater_DocPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be less than Document Period..
        /// </summary>
        internal static string ApplPeriod_Less_DocPeriod {
            get {
                return ResourceManager.GetString("ApplPeriod_Less_DocPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Balance Enquiry.
        /// </summary>
        internal static string ARCustomerBalanceEnq {
            get {
                return ResourceManager.GetString("ARCustomerBalanceEnq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Documents Enquiry.
        /// </summary>
        internal static string ARDocumentEnq {
            get {
                return ResourceManager.GetString("ARDocumentEnq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release AR documents.
        /// </summary>
        internal static string ARDocumentRelease {
            get {
                return ResourceManager.GetString("ARDocumentRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Invoices Enquiry.
        /// </summary>
        internal static string ARDueInvoicesEnq {
            get {
                return ResourceManager.GetString("ARDueInvoicesEnq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AR Invoice Entry.
        /// </summary>
        internal static string ARInvoiceEntry {
            get {
                return ResourceManager.GetString("ARInvoiceEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AR Payment Entry.
        /// </summary>
        internal static string ARPaymentEntry {
            get {
                return ResourceManager.GetString("ARPaymentEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AR Release Process.
        /// </summary>
        internal static string ARReleaseProcess {
            get {
                return ResourceManager.GetString("ARReleaseProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required configuration data is not entered into AR Setup..
        /// </summary>
        internal static string ARSetupNotFound {
            get {
                return ResourceManager.GetString("ARSetupNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process AR Statements.
        /// </summary>
        internal static string ARStatementProcess {
            get {
                return ResourceManager.GetString("ARStatementProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured during the process of statement regeneration.
        /// </summary>
        internal static string ARStatementRegenerationError {
            get {
                return ResourceManager.GetString("ARStatementRegenerationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balanced.
        /// </summary>
        internal static string Balanced {
            get {
                return ResourceManager.GetString("Balanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once applications are entered this field cannot be changed..
        /// </summary>
        internal static string Cannot_Change_Details_Exists {
            get {
                return ResourceManager.GetString("Cannot_Change_Details_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        internal static string Closed {
            get {
                return ResourceManager.GetString("Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Days Past Due Were Exceeded!.
        /// </summary>
        internal static string CreditDaysPastDueWereExceeded {
            get {
                return ResourceManager.GetString("CreditDaysPastDueWereExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Credit Limit Was Exceeded!.
        /// </summary>
        internal static string CreditLimitWasExceeded {
            get {
                return ResourceManager.GetString("CreditLimitWasExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Memo.
        /// </summary>
        internal static string CreditMemo {
            get {
                return ResourceManager.GetString("CreditMemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Class.
        /// </summary>
        internal static string CustomerClassMaint {
            get {
                return ResourceManager.GetString("CustomerClassMaint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        internal static string CustomerMaint {
            get {
                return ResourceManager.GetString("CustomerMaint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit Memo.
        /// </summary>
        internal static string DebitMemo {
            get {
                return ResourceManager.GetString("DebitMemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document is On Hold and cannot be released..
        /// </summary>
        internal static string Document_OnHold_CannotRelease {
            get {
                return ResourceManager.GetString("Document_OnHold_CannotRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Status is invalid for processing..
        /// </summary>
        internal static string Document_Status_Invalid {
            get {
                return ResourceManager.GetString("Document_Status_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry must be less or equal {0}.
        /// </summary>
        internal static string Entry_LE {
            get {
                return ResourceManager.GetString("Entry_LE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overdue Charge.
        /// </summary>
        internal static string FinCharge {
            get {
                return ResourceManager.GetString("FinCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial charge can not be created in this form! Use form Process Overdue Charges!.
        /// </summary>
        internal static string FinChargeCanNotBeDeleted {
            get {
                return ResourceManager.GetString("FinChargeCanNotBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Hold.
        /// </summary>
        internal static string Hold {
            get {
                return ResourceManager.GetString("Hold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice.
        /// </summary>
        internal static string Invoice {
            get {
                return ResourceManager.GetString("Invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiply Installments.
        /// </summary>
        internal static string MultiplyInstallmentsTranDesc {
            get {
                return ResourceManager.GetString("MultiplyInstallmentsTranDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter New Invoice.
        /// </summary>
        internal static string NewInvoice {
            get {
                return ResourceManager.GetString("NewInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter New Payment.
        /// </summary>
        internal static string NewPayment {
            get {
                return ResourceManager.GetString("NewPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Invoices and Credit adjustments may be payed.
        /// </summary>
        internal static string Only_Invoices_MayBe_Payed {
            get {
                return ResourceManager.GetString("Only_Invoices_MayBe_Payed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only documents having status &apos;open&apos; can be processed.
        /// </summary>
        internal static string Only_Open_Documents_MayBe_Processed {
            get {
                return ResourceManager.GetString("Only_Open_Documents_MayBe_Processed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Over Limit Amount Was Exceeded!.
        /// </summary>
        internal static string OverLimitWasExceeded {
            get {
                return ResourceManager.GetString("OverLimitWasExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        internal static string Payment {
            get {
                return ResourceManager.GetString("Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Refund.
        /// </summary>
        internal static string Refund {
            get {
                return ResourceManager.GetString("Refund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SalesPerson.
        /// </summary>
        internal static string SalesPerson {
            get {
                return ResourceManager.GetString("SalesPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SalesPerson Maintenance.
        /// </summary>
        internal static string SalesPersonMaint {
            get {
                return ResourceManager.GetString("SalesPersonMaint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled.
        /// </summary>
        internal static string Scheduled {
            get {
                return ResourceManager.GetString("Scheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date must be equal ot later then end date!.
        /// </summary>
        internal static string TempCrLimitInvalidDate {
            get {
                return ResourceManager.GetString("TempCrLimitInvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective periods in temporary credit limit history must not be crossed!.
        /// </summary>
        internal static string TempCrLimitPeriodsCrossed {
            get {
                return ResourceManager.GetString("TempCrLimitPeriodsCrossed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown document type  - unable to process..
        /// </summary>
        internal static string UnknownDocumentType {
            get {
                return ResourceManager.GetString("UnknownDocumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Void Check Payment Reference must match original payment..
        /// </summary>
        internal static string VoidAppl_CheckNbr_NotMatchOrigPayment {
            get {
                return ResourceManager.GetString("VoidAppl_CheckNbr_NotMatchOrigPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voided.
        /// </summary>
        internal static string Voided {
            get {
                return ResourceManager.GetString("Voided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Void Payment.
        /// </summary>
        internal static string VoidPayment {
            get {
                return ResourceManager.GetString("VoidPayment", resourceCulture);
            }
        }
    }
}
