using System;
using PX.Common;

namespace PX.Objects.CM
{
	[PXLocalizable(Messages.Prefix)]
	public static class Messages
	{
		#region Validation and Processing Messages
        public const string CurrencyInfo = "Currency Info";
		public const string Prefix = "CM Error";
		public const string CuryRateCantBeZero = "Currency rate cannot be set to zero.";
        public const string DestShouldDifferFromOrig = "The destination currency should be different from the source currency.";
		public const string InvalidField = "Invalid field: '{0}'.";
		public const string InvalidCache = "Missing CurrencyInfoAttribute for the cache: '{0}'.";
		public const string CuryIDCannotBeChanged = "{0} cannot be changed.";
		public const string RateIsNotDefinedForThisDate = "Rate is not defined for rate type '{0}' for currency '{1}' for this date!";
		public const string RateIsNotDefinedForThisDateVerbose = "Rate is not defined for rate type '{0}' from currency '{1}' to currency '{2}' for date {3}";
		public const string RateNotFound = "Currency Rate is not defined.";
		public const string RateTypeNotFound = "Currency Rate Type is not defined.";
		public const string TransactionCanNotBeDeleted = "Released or voided transaction can not be deleted!";
		public const string TransactionCanNotBeCreated = "Transaction can not be created!";
		public const string TranslDefIsAlreadyUsed = "Translation definition '{0}' is already used in existing translations!";
		public const string RateVarianceExceeded = "Rate variance exceeds the limit specified on the Currency Management Preferences form.";
		public const string CurrencyInfoNotSaved = "An error occurred while saving Currency Info for the table '{0}'";
		public const string RangeIntersectsWithRangeOnTheExistingDefinition = "The specified account/subaccount range should not intersect with the range '{1}{2} - {3}{4}' specified in the definition '{0}'.";
        public const string NotValidCombination = "Invalid Combination of Accounts and Subaccounts";
		public const string ThereAreNoTransactionsMade = "No new transactions have been generated by the translation process.";
		public const string FuturePeriodIsNotAvalableForTranslation = "Future Period Is Not Available For Translation";
		public const string DateNotBelongFinancialPeriod = "Currency rate effective date is outside the specified financial period.";
		public const string TranslationHistoryIsOutOfBalance = "Translation History is out of Balance";
		public const string TranslationOnPreviosPeriodNotReleased = "Translation On Previos Period Not Released";
		public const string TranslationDefinitionCanNotBeActive = "Translation definition can not be active";
		public const string TranslationDestinationLedegrIDCanNotBeChanged = "Translation Destination Ledeger ID can not be changed";
		public const string TranslationDestinationCurrencyMissingGOLAccounts = "To perform translation, specify Translation Loss/Gain Account (Subaccount) for currency {0}.";
		public const string TranslationDefinitionLedgerNotFound = "Translation Definition Ledger Not Found";
		public const string NotPostedBatchesExists = "There are unposted batches in the reporting branch/ledger. Post the batches before proceeding.";
		public const string NotReleasedTranslationExists = "Translation '{0}' is not released! Release or Delete this translation";
		public const string ReleasedTranslationExistsInGreaterPeriod = "Translation '{0}' is released in future period! Reverse this translation or create another one in the future period.";
		public const string YTDNetIncomeAccountWillBeExclude = "The range of accounts includes the YTD Net Income Account. Translation for this account will not be performed";
		public const string TranslationDefinitionHasSomeCrossIntervals = "Translation Definition has some cross intervals. So Translation cannot be created.";
		public const string SuchRateTypeAlreadyExist = "Such Currency Rate already exist";
		public const string NoRevaluationEntryWasMade = "No revaluation entry was made since Original Balance equals the Revalued Balance";
		public const string MultiCurrencyNotActivated = "Multi-Currency is not activated";
        public const string CurrencyNotSetupForOnlineRefresh = "Currency Rate Types have not been configured for online rate refresh. To use this feature, you must enable online refresh from the Currency Rate Types (CM.20.10.00) screen.";
        public const string NoOnlyRatesFoundForCurrency = "No exchange rate could be found online for currency {0}.";
        public const string CurrencyRateFailedToRefresh = "Rates for one or more currencies couldn't be refreshed.";
        public const string CurrencyRateRefreshDateInvalid = "You must enter a valid date. Rates can be refreshed up to the current date.";
        public const string CurrencyRateJsonError = "Error decoding response into valid JSON: {0}.";
        #endregion

		#region Translatable Strings used in the code
		public const string GLTranSuccessfullyCreated = "GLTran successfully created";
		public const string NothingSelected = "Nothing selected. Release not complete.";
		public const string Revalue = "Revalue";
		public const string Periods = "Periods";
		public const string CuryDisplayName = "Currency";
		#endregion

        #region CM Gain/Loss Mask Codes
        public const string MaskCurrency = "Currency";
        public const string MaskCompany = "Branch";
        #endregion

		#region Graph Names
		public const string CMSetupMaint = "Setup Currency Management";
		public const string CurrencyMaint = "Currencies Maintenance";
		public const string CurrencyRateTypeMaint = "Currencies Rate Types Maintenance";
		public const string CuryRateMaint = "Currencies Exchange Rate Maintenance";
		public const string TranslationDefinitionMaint = "Statement Transaltion Definition Maintenance";
		public const string TranslationEnq = "Statement Translaiton Entry";
		public const string TranslationProcess = "Statement Translation Preparation Process";
		public const string TranslationHistoryMaint = "Statement Translations History Inquiry";
		public const string TranslationRelease = "Statement Translation Release Process";
		public const string RevalueAPAccounts = "Revalue AP Accounts";
		public const string RevalueARAccounts = "Revalue AR Accounts";
		public const string RevalueGLAccounts = "Revalue GL Accounts";
		public const string CMSetup = "Currency Management Preferences";
		#endregion

		#region Cache Names
		public const string FinPeriodIsNotActive = "Fin Period is not Active";
		public const string TranslationHistory = "Translation History";
		public const string TranslationHistoryDetails = "Translation History Detail";
		public const string Currency = "Currency";
		public const string TranslDef = "Translation Definition";
		public const string TranslDefDet = "Translation Definition Detail";
        public const string CurrencyRate2 = "Effective Currency Rate";
        public const string CurrencyRate = "Currency Rate";
		public const string CurrencyRateByDate = "Currency Rate by Date";
		public const string CurrencyRateType = "Currency Rate Type";
		#endregion

		#region Combo Values
		//TranslationStatus and RevalStatus
		public const string Hold = "On Hold";
		public const string Balanced = "Balanced";
		public const string Released = "Released";
		public const string Voided = "Voided";

		//TranslationLineType
		public const string Translation = "Translation Line";
		public const string GainLoss = "Transl.Gain/Loss";
		#endregion

		#region Custom Actions
		public const string ViewTranslationBatch = "View Translation Batch";
		public const string ViewReversingBatch = "View Reversing Batch";
		public const string ViewTranslationDetails = "View Translation Details";
		public const string CreateTranslation = "Create Translation";
		public const string Release = "Release";
		public const string ReleaseAll = "Release All";
		public const string Reverse = "Reverse";
		public const string ViewBatch = "View Batch";
        public const string TranslationDetailsReport = "Translation Details";

		#endregion

		#region Tooltips
		public const string ToggleCurrencyViewTooltip = "Toggle Currency View";
		#endregion
	}
}